### ISSUE TITLE
Yangilik qo'shish

### ISSUE THREAD

**Issue by sanatillo** [sanatillo/dublincore#7]
Yangilik qo'shgan vaqtda,  qaysidir jurnallarni ichindagi maqolalardan parcha va rasm qoshammiz va shu jurnallarga ssilka saqlimiz. 
Demak bizlarda yangilik uchun alohida jadval yaratiladi:
id
mavzu
content (yanglikni matni)
link (jurnalga link - demak jurnal qo'shilgandan keyin qushiladi yangilik)
image (jurnaldan rasm)
datetime (create date)
avtor_id (user)

**Comment by sanatillo** [comment]
Yangiliklar bo'limida boshida shunday statyalardan parchalar turadi va pastda oxirgi chiqqan X jurnal ro'yhati turadi.
Agar sohaga oid qandaydir ma'lumotlar bo'lsa ularda jurnallarga ssilka bo'lmasa (yani jurnaldan olingan ma'lumot emas, xost upressni o'zi bo'lsa)unda bu yozuvda hech qanday jurnal gazetaga **link** saqlanmaydi

**Comment by Guljemile** [comment]
![image](https://user-images.githubusercontent.com/93268124/160144138-6c4066e2-a2a4-4a18-9749-95a698f1a6f4.png)

**Comment by sanatillo** [comment]
![image](https://user-images.githubusercontent.com/12523780/160843646-bb438de3-a9a2-49f4-9187-e18d8c0c4cfe.png)

**Comment by sanatillo** [comment]
Backend qismi bitkazildi
